version: '3.3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    network_mode: host
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    network_mode: host
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=localhost:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
      - KAFKA_BROKER_ID=2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.1
    container_name: schema-registry
    network_mode: host
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=localhost:29092
      - SCHEMA_REGISTRY_HOST_NAME=localhost
      - SCHEMA_REGISTRY_LISTENERS=http://localhost:8081
      - SCHEMA_REGISTRY_DEBUG=true
    depends_on:
      - kafka

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.0.1
    container_name: kafka-connect
    network_mode: host
    environment:
    - CONNECT_BOOTSTRAP_SERVERS=localhost:29092
    - CONNECT_REST_PORT=8083
    - CONNECT_GROUP_ID="quickstart"
    - CONNECT_CONFIG_STORAGE_TOPIC="quickstart-config"
    - CONNECT_OFFSET_STORAGE_TOPIC="quickstart-offsets"
    - CONNECT_STATUS_STORAGE_TOPIC="quickstart-status"
    - CONNECT_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
    - CONNECT_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
    - CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
    - CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
    - CONNECT_REST_ADVERTISED_HOST_NAME="localhost"
    - CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/filestream-connectors,/etc/kafka-connect/jars"
    volumes:
      - /tmp/quickstart/file:/tmp/quickstart
      - /tmp/quickstart/jars:/etc/kafka-connect/jars
    depends_on:
      - kafka

  kafka-connect-avro:
     image: confluentinc/cp-kafka-connect:7.0.1
     container_name: kafka-connect-avro
     network_mode: host
     environment:
       - CONNECT_BOOTSTRAP_SERVERS=localhost:29092
       - CONNECT_REST_PORT=8082
       - CONNECT_GROUP_ID="quickstart-avro"
       - CONNECT_CONFIG_STORAGE_TOPIC="quickstart-avro-config"
       - CONNECT_OFFSET_STORAGE_TOPIC="quickstart-avro-offsets"
       - CONNECT_STATUS_STORAGE_TOPIC="quickstart-avro-status"
       - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
       - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
       - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
       - CONNECT_KEY_CONVERTER="io.confluent.connect.avro.AvroConverter"
       - CONNECT_VALUE_CONVERTER="io.confluent.connect.avro.AvroConverter"
       - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL="http://localhost:8081"
       - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL="http://localhost:8081"
       - CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
       - CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
       - CONNECT_REST_ADVERTISED_HOST_NAME="localhost"
       - CONNECT_LOG4J_ROOT_LOGLEVEL=DEBUG
       - CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/filestream-connectors,/etc/kafka-connect/jars"
     volumes:
       - /tmp/quickstart/file:/tmp/quickstart
       - /tmp/quickstart/jars:/etc/kafka-connect/jars
     depends_on:
       - kafka

  mysql:
    image: mysql
    container_name: quickstart-mysql
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=confluent
      - MYSQL_USER=confluent
      - MYSQL_PASSWORD=confluent
      - MYSQL_DATABASE=connect_test

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    network_mode: host
    environment:
      - SERVER_PORT=8000
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:32181
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://localhost:8081
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=kafka-connect
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://localhost:8083
